# Using a slim version for a smaller base image
FROM python:3.10-slim-bullseye

RUN apt-get update

WORKDIR /app

COPY tutor_mistakes/requirements.txt .

# Upgrade pip
RUN pip install --upgrade pip

# Increase timeout to wait for the new installation
RUN pip install --no-cache-dir -r requirements.txt

ENV LANG="C.UTF-8"

COPY tutor_mistakes /app/tutor_mistakes

WORKDIR /app/tutor_mistakes
